### ISSUE TITLE
启动配置

### ISSUE THREAD

**Issue by imjyz** [WGrape/esupdater#41]
![image](https://user-images.githubusercontent.com/31824316/148953732-bfcbdd1d-e283-4259-b1f0-66ad0dcb5bec.png)

这里的配置，放在执行 install.sh 时以参数传入，可能更合适。

**Comment by WGrape** [comment]
非常好的提议，可以在执行 install.sh 安装脚本的时候 ，把一些参数传入写入环境变量/系统变量中。

已经在修改中，修改完成后会在此 issue 中回复，感谢支持 ~

**Comment by WGrape** [comment]
在 v2.x 分支中的 [commit551c5585d8](https://github.com/WGrape/esupdater/commit/551c5585d878ec3ebe72c142cb294aa37c64ed29) 已经完成修改。

感谢反馈 ~
