### ISSUE TITLE
如果handler和service层可以自动生成就完美了

### ISSUE THREAD

**Issue by onser3** [WGrape/esupdater#44]

**Comment by WGrape** [comment]
很好的建议 ，此功能已在计划开发中 ，关注项目和此 Issue ，完成后会第一时间通知 。

感谢反馈 ~

**Comment by WGrape** [comment]
你好，功能已实现。

源码见 Commit ：[添加插件扩展功能-完成第一个扩展autogeneratecallback](https://github.com/WGrape/esupdater/commit/e1408c5b8aa9c9dfa3bc89092026974806197069)

此功能目录和使用介绍请[参考文档](https://github.com/WGrape/esupdater/tree/v2.x/plugin/autogeneratecallback)
